import{Router}from'express';import multer from'multer';import crypto from'node:crypto';import path from'node:path';import fs from'node:fs/promises';import{fileURLToPath}from'node:url';import{z}from'zod';import{db}from'../../config/db.js';import{requireAuthentication}from'../../middleware/authentication.js';import{requirePermission}from'../../middleware/authorization.js';
const HERE=path.dirname(fileURLToPath(import.meta.url));
const ROOT=process.env.UPLOAD_ROOT?path.resolve(process.env.UPLOAD_ROOT):path.resolve(HERE,'../../../../storage/uploads');
const DIR=path.join(ROOT,'report-signatures');
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024,files:1}});
const meta=z.object({signerRole:z.literal('KEPALA_MADRASAH'),signerName:z.string().trim().min(1).max(150),signerTitle:z.string().trim().min(1).max(150)}).strict();
export const reportSignatureRouter=Router();reportSignatureRouter.use(requireAuthentication);
function full(rel:string){const p=path.resolve(ROOT,rel);return p.startsWith(ROOT+path.sep)?p:null}
function sendFileErrorStatus(e:Error&{statusCode?:number}){return e.statusCode===404?404:500}
reportSignatureRouter.get('/',requirePermission('report.signatures.manage'),async(_req,res,next)=>{try{const[rows]=await db.query(`SELECT id,signer_role,signer_name,signer_title,file_size,sha256,active,uploaded_by,created_at FROM report_signature_assets WHERE signer_role='KEPALA_MADRASAH' ORDER BY active DESC,created_at DESC`);res.json({signatures:rows})}catch(e){next(e)}});
reportSignatureRouter.post('/',requirePermission('report.signatures.manage'),upload.single('file'),async(req,res,next)=>{let saved:string|undefined;try{const m=meta.safeParse(req.body);const f=req.file;if(!m.success||!f||f.mimetype!=='application/pdf'||f.buffer.subarray(0,5).toString()!=='%PDF-'){res.status(400).json({error:'INVALID_REPORT_SIGNATURE_PDF'});return}const d=m.data;const digest=crypto.createHash('sha256').update(f.buffer).digest('hex');await fs.mkdir(DIR,{recursive:true});const name=crypto.randomUUID()+'.pdf';await fs.writeFile(path.join(DIR,name),f.buffer,{flag:'wx'});saved=`report-signatures/${name}`;const c=await db.getConnection();try{await c.beginTransaction();await c.execute(`UPDATE report_signature_assets SET active=0 WHERE signer_role='KEPALA_MADRASAH' AND active=1`);const[r]:any=await c.execute(`INSERT INTO report_signature_assets(signer_role,teacher_id,signer_name,signer_title,file_path,mime_type,file_size,sha256,active,uploaded_by) VALUES('KEPALA_MADRASAH',NULL,?,?,?,?,?,?,1,?)`,[d.signerName,d.signerTitle,saved,'application/pdf',f.size,digest,req.auth!.userId]);await c.commit();res.status(201).json({id:r.insertId,sha256:digest})}catch(e){await c.rollback();throw e}finally{c.release()}}catch(e){if(saved){const p=full(saved);if(p)await fs.unlink(p).catch(()=>{})}next(e)}});
reportSignatureRouter.patch('/:id/deactivate',requirePermission('report.signatures.manage'),async(req,res,next)=>{try{const id=Number(req.params.id);if(!Number.isSafeInteger(id)||id<=0){res.status(400).json({error:'INVALID_SIGNATURE_ID'});return}const[r]:any=await db.execute(`UPDATE report_signature_assets SET active=0 WHERE id=? AND signer_role='KEPALA_MADRASAH' AND active=1`,[id]);if(!r.affectedRows){res.status(404).json({error:'ACTIVE_SIGNATURE_NOT_FOUND'});return}res.status(204).end()}catch(e){next(e)}});
reportSignatureRouter.get('/:id/file',async(req,res,next)=>{try{const id=Number(req.params.id);if(!Number.isSafeInteger(id)||id<=0){res.status(400).end();return}const[r]:any=await db.query(`SELECT rsa.file_path,rsa.mime_type FROM report_signature_assets rsa WHERE rsa.id=? AND rsa.signer_role='KEPALA_MADRASAH' AND (rsa.active=1 OR EXISTS(SELECT 1 FROM reports rp WHERE JSON_CONTAINS(COALESCE(rp.snapshot_json,JSON_OBJECT()),JSON_OBJECT('id',rsa.id),'$.signatures.kepala'))) LIMIT 1`,[id]);if(!r[0]){res.status(404).end();return}const allowed=req.auth!.role==='ADMIN'||req.auth!.role==='SUPER_ADMIN';if(!allowed){res.status(403).end();return}const p=full(r[0].file_path);if(!p){res.status(500).end();return}res.type(r[0].mime_type);res.setHeader('Content-Disposition','inline; filename="signature.pdf"');res.sendFile(p,e=>{if(e&&!res.headersSent)res.status(sendFileErrorStatus(e)).end()})}catch(e){next(e)}});
