import { FormEvent,useEffect,useState } from 'react';
import {api,ApiError} from '../../services/api';
type Field={key:string;label:string;type?:string;required?:boolean;options?:string[];source?:string;min?:number;max?:number};
const field=(key:string,label:string,type='text',required=false):Field=>({key,label,type,required});
const ref=(key:string,label:string,source:string):Field=>({key,label,source,required:true});
const configs:Record<string,{title:string;fields:Field[]}>= {
 teachers:{title:'Guru',fields:[field('code','Kode guru'),field('name','Nama','text',true),field('nip_or_identifier','Nomor identitas'),{key:'status',label:'Status',options:['ACTIVE','INACTIVE']}]},
 classes:{title:'Kelas',fields:[field('code','Kode kelas','text',true),{...field('level','Tingkat','number',true),min:1,max:6},field('name','Nama kelas'),field('room_name','Ruang'),field('floor_name','Lantai'),field('active','Aktif','checkbox')]},
 subjects:{title:'Mata Pelajaran',fields:[field('code','Kode'),field('name','Nama','text',true),field('book_name','Kitab'),field('active','Aktif','checkbox')]},
 years:{title:'Tahun Ajaran',fields:[field('name','Tahun ajaran','text',true),field('starts_on','Mulai','date',true),field('ends_on','Selesai','date',true),field('is_active','Tahun aktif','checkbox')]},
 assignments:{title:'Penugasan Mengajar',fields:[ref('teacher_id','Guru','teachers'),ref('class_id','Kelas','classes'),ref('subject_id','Mata pelajaran','subjects'),ref('academic_year_id','Tahun ajaran','years'),{key:'semester',label:'Semester',options:['GANJIL','GENAP']},field('active','Aktif','checkbox')]},
 homerooms:{title:'Wali Kelas / Musrif',fields:[ref('teacher_id','Guru','teachers'),ref('class_id','Kelas','classes'),ref('academic_year_id','Tahun ajaran','years'),{key:'assignment_type',label:'Tugas',options:['WALI_KELAS','MUSRIF']},field('active','Aktif','checkbox')]},
};
export default function OperationsPage({initial='teachers'}:{initial?:string}){
 const[resource,setResource]=useState(initial),[rows,setRows]=useState<any[]>([]),[lookups,setLookups]=useState<Record<string,any[]>>({}),[edit,setEdit]=useState<Record<string,any>|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 const cfg=configs[resource];
 async function load(){setLoading(true);try{const sources=[...new Set(cfg.fields.map(f=>f.source).filter(Boolean))] as string[];const[data,options]=await Promise.all([api<{rows:any[]}>('/operations/'+resource),Promise.all(sources.map(async s=>[s,(await api<{rows:any[]}>('/operations/'+s)).rows] as const))]);setRows(data.rows);setLookups(Object.fromEntries(options));}catch(e){setError(e instanceof ApiError?e.code:'Gagal memuat data.')}finally{setLoading(false)}}
 useEffect(()=>{setEdit(null);setError('');void load()},[resource]);
 const name=(s:string,id:any)=>{const r=lookups[s]?.find(r=>Number(r.id)===Number(id));return r?[r.code,r.name].filter(Boolean).join(' · '):'Belum dipilih'};
 function create(){setEdit(Object.fromEntries(cfg.fields.map(f=>[f.key,f.type==='checkbox'?true:f.options?.[0]??''])))}
 async function save(e:FormEvent){e.preventDefault();if(!edit||busy)return;setBusy(true);setError('');try{const body=Object.fromEntries(cfg.fields.map(f=>[f.key,f.type==='checkbox'?Boolean(edit[f.key]):(f.type==='number'||f.source)?Number(edit[f.key]):edit[f.key]===''?null:edit[f.key]]));await api('/operations/'+resource+(edit.id?'/'+edit.id:''),{method:edit.id?'PUT':'POST',body:JSON.stringify(body)});setEdit(null);await load()}catch(e){setError(e instanceof ApiError?e.code:'Gagal menyimpan.')}finally{setBusy(false)}}
 return <section className="card"><div className="filters"><label>Administrasi<select value={resource} onChange={e=>setResource(e.target.value)} disabled={busy}>{Object.entries(configs).map(([k,v])=><option key={k} value={k}>{v.title}</option>)}</select></label><button onClick={create} disabled={busy}>Tambah {cfg.title}</button></div>{error&&<p role="alert" className="error">{error}</p>}{loading?<p>Memuat…</p>:<div className="tableWrap"><table><thead><tr>{cfg.fields.map(f=><th key={f.key}>{f.label}</th>)}<th>Aksi</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}>{cfg.fields.map(f=><td key={f.key}>{f.source?name(f.source,r[f.key]):f.type==='checkbox'?(r[f.key]?'Ya':'Tidak'):r[f.key]??'—'}</td>)}<td><button onClick={()=>setEdit(r)}>Ubah</button></td></tr>)}</tbody></table>{!rows.length&&<p>Belum ada data.</p>}</div>}{edit&&<form className="card" onSubmit={save}><h3>{edit.id?'Ubah':'Tambah'} {cfg.title}</h3>{['assignments','homerooms'].includes(resource)&&edit.id&&<p>Untuk mengganti penugasan, nonaktifkan yang lama lalu tambahkan penugasan baru agar histori tetap tersimpan.</p>}<div className="filters">{cfg.fields.map(f=><label key={f.key}>{f.label}{f.source?<select required value={edit[f.key]??''} onChange={e=>setEdit({...edit,[f.key]:e.target.value})}><option value="">Pilih…</option>{lookups[f.source]?.map(r=><option key={r.id} value={r.id}>{[r.code,r.name].filter(Boolean).join(' · ')}</option>)}</select>:f.options?<select value={edit[f.key]??f.options[0]} onChange={e=>setEdit({...edit,[f.key]:e.target.value})}>{f.options.map(v=><option key={v}>{v}</option>)}</select>:f.type==='checkbox'?<input type="checkbox" checked={Boolean(edit[f.key])} onChange={e=>setEdit({...edit,[f.key]:e.target.checked})}/>:<input type={f.type} required={f.required} min={f.min} max={f.max} value={edit[f.key]??''} onChange={e=>setEdit({...edit,[f.key]:e.target.value})}/>}</label>)}</div><button disabled={busy}>Simpan</button> <button type="button" disabled={busy} onClick={()=>setEdit(null)}>Batal</button></form>}</section>
}
