import{FormEvent,useEffect,useState}from'react';import{api,ApiError}from'../../services/api';
type Role='SUPER_ADMIN'|'ADMIN'|'GURU'|'SANTRI';
function Table({rows}:{rows:any[]}){if(!rows.length)return <p>Belum ada data.</p>;const keys=Object.keys(rows[0]).filter(k=>!['photo_path','snapshot_json','file_path'].includes(k));return <div className="tableWrap"><table><thead><tr>{keys.map(k=><th key={k}>{k.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id??i}>{keys.map(k=><td key={k}>{r[k]===null||r[k]===undefined?'—':typeof r[k]==='object'?JSON.stringify(r[k]):String(r[k])}</td>)}</tr>)}</tbody></table></div>}
export default function ProductionPage({page,role}:{page:string;role:Role}){const[data,setData]=useState<any[]|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function load(){setData(null);setError('');let path:string|undefined,key:string|undefined;if(page==='Santri Kelas'&&role==='GURU'){path='/teachers/me/students';key='students'}else if(page==='Profil'&&role==='SANTRI'){path='/student/me';key='student'}else if(page==='Kalender'){path='/support/calendar';key='events'}else if(page==='Pengumuman'){path='/support/announcements';key='announcements'}else if(page==='Kritik & Saran'&&role==='GURU'){path='/support/feedback/me';key='feedback'}else if(page==='Notifikasi'){path='/support/notifications/me';key='notifications'}if(!path){setData([]);return;}try{const r=await api<any>(path);setData(Array.isArray(r[key!])?r[key!]:r[key!]?[r[key!]]:[])}catch(e){setError(e instanceof ApiError?e.code:'Gagal memuat data.')}}
 useEffect(()=>{setMessage('');void load()},[page,role]);
 async function submit(e:FormEvent<HTMLFormElement>,kind:'calendar'|'announcement'|'feedback'){e.preventDefault();if(busy)return;const f=new FormData(e.currentTarget);setBusy(true);setError('');setMessage('');try{let body:any;if(kind==='calendar')body={academicYearId:null,title:String(f.get('title')),startsOn:String(f.get('startsOn')),endsOn:String(f.get('endsOn')),category:String(f.get('category')),locksAttendance:f.get('locksAttendance')==='on',description:String(f.get('description')||'')||null};else if(kind==='announcement')body={title:String(f.get('title')),body:String(f.get('body')),audience:String(f.get('audience')),publish:f.get('publish')==='on'};else body={category:String(f.get('category')),title:String(f.get('title')),message:String(f.get('message'))};await api('/support/'+(kind==='calendar'?'calendar':kind==='announcement'?'announcements':'feedback'),{method:'POST',body:JSON.stringify(body)});e.currentTarget.reset();setMessage('Tersimpan.');await load()}catch(e){setError(e instanceof ApiError?e.code:'Gagal menyimpan data.')}finally{setBusy(false)}}
 const manager=['ADMIN','SUPER_ADMIN'].includes(role);
 if(error&&data===null)return <section className="card"><p className="error">{error}</p></section>;if(data===null)return <section className="card"><p>Memuat data…</p></section>;
 return <section className="card"><h2>{page}</h2>{message&&<p role="status">{message}</p>}{error&&<p role="alert" className="error">{error}</p>}
 {page==='Kalender'&&manager&&<form className="card" onSubmit={e=>submit(e,'calendar')}><h3>Tambah Agenda</h3><div className="filters"><label>Judul<input name="title" required maxLength={200}/></label><label>Mulai<input name="startsOn" type="date" required/></label><label>Selesai<input name="endsOn" type="date" required/></label><label>Kategori<select name="category">{['KBM','UJIAN','LIBUR','PONDOK','MUHAFADLOH','LAINNYA'].map(x=><option key={x}>{x}</option>)}</select></label><label><input name="locksAttendance" type="checkbox"/> Kunci absensi</label><label>Keterangan<input name="description" maxLength={3000}/></label></div><button disabled={busy}>Simpan Agenda</button></form>}
 {page==='Pengumuman'&&manager&&<form className="card" onSubmit={e=>submit(e,'announcement')}><h3>Buat Pengumuman</h3><div className="filters"><label>Judul<input name="title" required maxLength={255}/></label><label>Isi<textarea name="body" required maxLength={20000}/></label><label>Penerima<select name="audience"><option>ALL</option><option>GURU</option><option>SANTRI</option></select></label><label><input name="publish" type="checkbox"/> Publikasikan sekarang</label></div><button disabled={busy}>Simpan Pengumuman</button></form>}
 {page==='Kritik & Saran'&&role==='GURU'&&<form className="card" onSubmit={e=>submit(e,'feedback')}><h3>Kirim Kritik & Saran</h3><div className="filters"><label>Kategori<select name="category">{['KURIKULUM','KEDISIPLINAN','FASILITAS','SANTRI','LAINNYA'].map(x=><option key={x}>{x}</option>)}</select></label><label>Judul<input name="title" required maxLength={255}/></label><label>Pesan<textarea name="message" required maxLength={10000}/></label></div><button disabled={busy}>Kirim</button></form>}
 <Table rows={data}/></section>}
